const styles = {
  page: {
    minHeight: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "linear-gradient(135deg,#0f172a 0%,#1e3a5f 100%)",
    fontFamily: "'Segoe UI', sans-serif",
    padding: "1rem",
  },
  card: {
    background: "#ffffff",
    borderRadius: "16px",
    padding: "2.5rem 2rem",
    width: "100%",
    maxWidth: "400px",
    boxShadow: "0 20px 60px rgba(0,0,0,0.35)",
  },

  title:    { margin: "0 0 4px", fontSize: "1.8rem", color: "#0f172a" },
  subtitle: { margin: "0 0 1.5rem", fontSize: ".875rem", color: "#64748b" },
  label:    { display: "block", fontSize: ".8rem", fontWeight: 600, color: "#334155", marginBottom: "6px" },
  errMsg:   { fontSize: ".78rem", color: "#ef4444", marginTop: "4px", display: "block" },

  field:     { marginBottom: "1.1rem" },
  input: {
    width: "100%",
    padding: "10px 14px",
    border: "1.5px solid #cbd5e1",
    borderRadius: "8px",
    fontSize: ".95rem",
    outline: "none",
    boxSizing: "border-box",
    transition: "border-color .2s",
  },
  inputErr:  { borderColor: "#ef4444" },
  passWrap:  { position: "relative" },
  passInput: { paddingRight: "44px" },
  eyeBtn: {
    position: "absolute",
    right: "10px",
    top: "50%",
    transform: "translateY(-50%)",
    background: "none",
    border: "none",
    cursor: "pointer",
    fontSize: "1rem",
    padding: "0",
  },

  alertError: {
    background: "#fef2f2",
    border: "1px solid #fecaca",
    color: "#dc2626",
    borderRadius: "8px",
    padding: "10px 14px",
    fontSize: ".85rem",
    marginBottom: "1rem",
  },

  btnSubmit: {
    width: "100%",
    padding: "12px",
    background: "linear-gradient(135deg,#1e3a8a,#3b82f6)",
    color: "#fff",
    border: "none",
    borderRadius: "8px",
    fontSize: "1rem",
    fontWeight: 600,
    cursor: "pointer",
    marginTop: ".5rem",
    transition: "opacity .2s",
  },
  btnLogout: {
    padding: "10px 32px",
    background: "#ef4444",
    color: "#fff",
    border: "none",
    borderRadius: "8px",
    fontSize: ".95rem",
    fontWeight: 600,
    cursor: "pointer",
  },

  hint: {
    marginTop: "1.4rem",
    padding: "12px",
    background: "#f1f5f9",
    borderRadius: "8px",
    fontSize: ".78rem",
    color: "#475569",
    lineHeight: 1.7,
   }, 
  
  avatar: {
    width: "64px",
    height: "64px",
    borderRadius: "50%",
    background: "linear-gradient(135deg,#1e3a8a,#3b82f6)",
    color: "#fff",
    fontSize: "1.8rem",
    fontWeight: 700,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    margin: "0 auto 1rem",
  },
  welcomeTitle: { margin: "0 0 4px", fontSize: "1.5rem", color: "#0f172a" },
  welcomeName:  { margin: "0 0 .75rem", fontSize: "1.1rem", color: "#334155" },
  badge: {
    display: "inline-block",
    padding: "3px 12px",
    borderRadius: "999px",
    color: "#fff",
    fontSize: ".75rem",
    fontWeight: 700,
    marginBottom: ".75rem",
  },
  info: { fontSize: ".82rem", color: "#64748b", margin: "0 0 1.5rem" },
};

export default styles;

